# Generated by Django 6.0.2 on 2026-02-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='post',
            name='estaminated_readtime',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
